## Importing pandas

### Getting started and checking your pandas setup

Difficulty: *easy* 

**1.** Import pandas under the alias `pd`.

In [2]:
import pandas as pd
import numpy as np

**2.** Print the version of pandas that has been imported.

In [2]:
pip show pandas

Name: pandas
Version: 1.3.5
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: https://pandas.pydata.org
Author: The Pandas Development Team
Author-email: pandas-dev@python.org
License: BSD-3-Clause
Location: c:\users\asus\appdata\local\programs\python\python37\lib\site-packages
Requires: numpy, python-dateutil, pytz
Required-by: seaborn
Note: you may need to restart the kernel to use updated packages.


**3.** Print out all the *version* information of the libraries that are required by the pandas library.

In [7]:
print(pd. __version__)


1.3.5


## DataFrame basics

### A few of the fundamental routines for selecting, sorting, adding and aggregating data in DataFrames

Difficulty: *easy*

Note: remember to import numpy using:
```python
import numpy as np
```

Consider the following Python dictionary `data` and Python list `labels`:

``` python
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
(This is just some meaningless data I made up with the theme of animals and trips to a vet.)

**4.** Create a DataFrame `df` from this dictionary `data` which has the index `labels`.

In [3]:
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data,index=labels)
df

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

**5.** Display a summary of the basic information about this DataFrame and its data (*hint: there is a single method that can be called on the DataFrame*).

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   animal    10 non-null     object 
 1   age       8 non-null      float64
 2   visits    10 non-null     int64  
 3   priority  10 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes


**6.** Return the first 3 rows of the DataFrame `df`.

In [9]:
df.head(3)

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

**7.** Select just the 'animal' and 'age' columns from the DataFrame `df`.

In [18]:
#df.iloc[0:,0:2]
df.loc[:,['animal','age']]

animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

**8.** Select the data in rows `[3, 4, 8]` *and* in columns `['animal', 'age']`.

In [26]:
df.iloc[[3, 4, 8], [0, 1]]

animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

**9.** Select only the rows where the number of visits is greater than 3.

In [5]:
df = pd.DataFrame(data,index=labels)
dfvist=df.loc[:,['visits']]
df[dfvist >=3]

animal  age  visits priority
a    NaN  NaN     NaN      NaN
b    NaN  NaN     3.0      NaN
c    NaN  NaN     NaN      NaN
d    NaN  NaN     3.0      NaN
e    NaN  NaN     NaN      NaN
f    NaN  NaN     3.0      NaN
g    NaN  NaN     NaN      NaN
h    NaN  NaN     NaN      NaN
i    NaN  NaN     NaN      NaN
j    NaN  NaN     NaN      NaN

**10.** Select the rows where the age is missing, i.e. it is `NaN`.

In [51]:
Findnan=df[df['age'].isnull()]
Findnan

animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes

**11.** Select the rows where the animal is a cat *and* the age is less than 3.

In [60]:
findanimalcat=df[(df['animal']=='cat') &  (df['age']==3)]
#findanimalcat=(df['animal']=='cat') &  (df['age']==3)
findanimalcat

animal  age  visits priority
b    cat  3.0       3      yes

**12.** Select the rows the age is between 2 and 4 (inclusive).

In [63]:
findagebtn=df[(df['age']>=2) &  (df['age']<=4)]
findagebtn

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
f    cat  2.0       3       no
j    dog  3.0       1       no

**13.** Change the age in row 'f' to 1.5.

In [79]:
#fupdate=df.loc[df['animal'] == 'cat', 'age'] = 1.5
fupdate=df.at[8,'age']=1.5
fupdate

1.5

**14.** Calculate the sum of all visits in `df` (i.e. find the total number of visits).

In [80]:
sumvisits=df['visits'].sum()
sumvisits

19.0

**15.** Calculate the mean age for each different animal in `df`.

In [82]:
meanage=df.groupby('animal')['age'].mean()
meanage

animal
cat      1.5
dog      5.0
snake    2.5
Name: age, dtype: float64

**16.** Append a new row 'k' to `df` with your choice of values for each column. Then delete that row to return the original DataFrame.

In [10]:
newrow={'animal':'lion','age':3,'visits':2,'priorty':'no'}
newrowdf=df.append(newrow,ignore_index=True)
newrowdf
removenewrow=newrowdf.drop(newrowdf.index[-1])
removenewrow


animal  age  visits priority priorty
0    cat  2.5       1      yes     NaN
1    cat  3.0       3      yes     NaN
2  snake  0.5       2       no     NaN
3    dog  NaN       3      yes     NaN
4    dog  5.0       2       no     NaN
5    cat  2.0       3       no     NaN
6  snake  4.5       1       no     NaN
7    cat  NaN       1      yes     NaN
8    dog  7.0       2       no     NaN
9    dog  3.0       1       no     NaN

**17.** Count the number of each type of animal in `df`.

In [85]:
countanimal=df.groupby('animal')['age'].count()
countanimal

animal
cat      4
dog      3
snake    2
Name: age, dtype: int64

**18.** Sort `df` first by the values in the 'age' in *decending* order, then by the value in the 'visits' column in *ascending* order (so row `i` should be first, and row `d` should be last).

In [17]:
#fillnull=df.fillna(0)
sortdata=df.sort_values(by=['age','visits'],ascending=[False,True])
sortdata

animal  age  visits priority
i    dog  7.0       2       no
e    dog  5.0       2       no
g  snake  4.5       1       no
j    dog  3.0       1       no
b    cat  3.0       3      yes
a    cat  2.5       1      yes
f    cat  2.0       3       no
c  snake  0.5       2       no
h    cat  NaN       1      yes
d    dog  NaN       3      yes

**19.** The 'priority' column contains the values 'yes' and 'no'. Replace this column with a column of boolean values: 'yes' should be `True` and 'no' should be `False`.

In [23]:
prioritycolumupdate=df
prioritycolumupdate['priority']=prioritycolumupdate['priority'].replace({'yes':True , 'No': False})
prioritycolumupdate

animal  age  visits priority
a    cat  2.5       1     True
b    cat  3.0       3     True
c  snake  0.5       2       no
d    dog  NaN       3     True
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1     True
i    dog  7.0       2       no
j    dog  3.0       1       no

**20.** In the 'animal' column, change the 'snake' entries to 'python'.

In [26]:
changesnaketopython=df
changesnaketopython['animal']=changesnaketopython['animal'].replace('snake','python')
changesnaketopython


animal  age  visits priority
a     cat  2.5       1     True
b     cat  3.0       3     True
c  python  0.5       2       no
d     dog  NaN       3     True
e     dog  5.0       2       no
f     cat  2.0       3       no
g  python  4.5       1       no
h     cat  NaN       1     True
i     dog  7.0       2       no
j     dog  3.0       1       no

**21.** For each animal type and each number of visits, find the mean age. In other words, each row is an animal, each column is a number of visits and the values are the mean ages (*hint: use a pivot table*).

In [30]:
pivottable=df.pivot_table(values='age',index='animal',columns='visits',aggfunc='mean')
pivottable

visits    1    2    3
animal               
cat     2.5  NaN  2.5
dog     3.0  6.0  NaN
python  4.5  0.5  NaN

## DataFrames: beyond the basics

### Slightly trickier: you may need to combine two or more methods to get the right answer

Difficulty: *medium*

The previous section was tour through some basic but essential DataFrame operations. Below are some ways that you might need to cut your data, but for which there is no single "out of the box" method.

**22.** You have a DataFrame `df` with a column 'A' of integers. For example:
```python
df = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
```

How do you filter out rows which contain the same integer as the row immediately above?

You should be left with a column containing the following values:

```python
1, 2, 3, 4, 5, 6, 7
```

In [4]:
df = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
df
notprintimeediatevalue=df[df['A'] != df['A'].shift(1)]
notprintimeediatevalue

A
0  1
1  2
3  3
4  4
5  5
8  6
9  7

**23.** Given a DataFrame of numeric values, say
```python
df = pd.DataFrame(np.random.random(size=(5, 3))) # a 5x3 frame of float values
```

how do you subtract the row mean from each element in the row?

In [9]:
import numpy as np
df = pd.DataFrame(np.random.random(size=(5, 3)))
print(df)
df_subtracted = df.sub(df.mean(axis=1), axis=0)
df_subtracted

          0         1         2
0  0.403242  0.991349  0.632581
1  0.153385  0.756118  0.012095
2  0.473417  0.207654  0.738086
3  0.357761  0.330579  0.983233
4  0.709737  0.444866  0.911155


0         1         2
0 -0.272482  0.315625 -0.043143
1 -0.153814  0.448919 -0.295104
2  0.000365 -0.265398  0.265034
3 -0.199430 -0.226612  0.426042
4  0.021151 -0.243720  0.222569

**24.** Suppose you have DataFrame with 10 columns of real numbers, for example:

```python
df = pd.DataFrame(np.random.random(size=(5, 10)), columns=list('abcdefghij'))
```
Which column of numbers has the smallest sum?  Return that column's label.

In [13]:
df = pd.DataFrame(np.random.random(size=(5, 10)), columns=list('abcdefghij'))
print(df)
min_sum_column = df.sum().idxmin()
min_sum_column

          a         b         c         d         e         f         g  \
0  0.968221  0.350883  0.337510  0.428339  0.606852  0.247664  0.898464   
1  0.464711  0.095245  0.674504  0.204334  0.729468  0.007075  0.217608   
2  0.292349  0.393877  0.093155  0.555504  0.554376  0.002499  0.993660   
3  0.986561  0.301018  0.199107  0.721400  0.329682  0.912009  0.244131   
4  0.495209  0.297654  0.434170  0.727318  0.220958  0.686832  0.815450   

          h         i         j  
0  0.275941  0.316762  0.575003  
1  0.657106  0.491398  0.034666  
2  0.300457  0.983552  0.420777  
3  0.275732  0.946009  0.994863  
4  0.242819  0.455723  0.550576  


'b'

**25.** How do you count how many unique rows a DataFrame has (i.e. ignore all rows that are duplicates)? As input, use a DataFrame of zeros and ones with 10 rows and 3 columns.

```python
df = pd.DataFrame(np.random.randint(0, 2, size=(10, 3)))
```

In [17]:
df = pd.DataFrame(np.random.randint(0, 2, size=(10, 3)))
print(df)
removedup=df.drop_duplicates().shape[0]
removedup

   0  1  2
0  0  1  0
1  1  0  0
2  0  0  1
3  0  0  1
4  0  0  1
5  1  0  1
6  0  0  1
7  0  1  0
8  1  1  1
9  0  0  1


5

The next three puzzles are slightly harder.


**26.** In the cell below, you have a DataFrame `df` that consists of 10 columns of floating-point numbers. Exactly 5 entries in each row are NaN values. 

For each row of the DataFrame, find the *column* which contains the *third* NaN value.

You should return a Series of column labels: `e, c, d, h, d`

In [6]:
nan = np.nan

data = [[0.04,  nan,  nan, 0.25,  nan, 0.43, 0.71, 0.51,  nan,  nan],
        [ nan,  nan,  nan, 0.04, 0.76,  nan,  nan, 0.67, 0.76, 0.16],
        [ nan,  nan, 0.5 ,  nan, 0.31, 0.4 ,  nan,  nan, 0.24, 0.01],
        [0.49,  nan,  nan, 0.62, 0.73, 0.26, 0.85,  nan,  nan,  nan],
        [ nan,  nan, 0.41,  nan, 0.05,  nan, 0.61,  nan, 0.48, 0.68]]

columns = list('abcdefghij')

df = pd.DataFrame(data, columns=columns)
df
def find_third_nan(column_values):
    nan_count = 0
    for i, value in enumerate(column_values):
        if pd.isna(value):
            nan_count += 1
            if nan_count == 3:
                return df.columns[i]

# Apply the custom function to each row
result_series = df.apply(find_third_nan, axis=1)

# Display the result Series
print(result_series)

# write a solution to the question here

0    e
1    c
2    d
3    h
4    d
dtype: object


**27.** A DataFrame has a column of groups 'grps' and and column of integer values 'vals': 

```python
df = pd.DataFrame({'grps': list('aaabbcaabcccbbc'), 
                   'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]})
```
For each *group*, find the sum of the three greatest values. You should end up with the answer as follows:
```
grps
a    409
b    156
c    345
```

In [11]:
df = pd.DataFrame({'grps': list('aaabbcaabcccbbc'), 
                   'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]})
df
sortthevalue=df.sort_values(by='vals',ascending=False).groupby('grps').head(3)
sumthrvalues=sortthevalue.groupby('grps')['vals'].sum()
sumthrvalues

# write a solution to the question here

grps
a    409
b    156
c    345
Name: vals, dtype: int64

**28.** The DataFrame `df` constructed below has two integer columns 'A' and 'B'. The values in 'A' are between 1 and 100 (inclusive). 

For each group of 10 consecutive integers in 'A' (i.e. `(0, 10]`, `(10, 20]`, ...), calculate the sum of the corresponding values in column 'B'.

The answer should be a Series as follows:

```
A
(0, 10]      635
(10, 20]     360
(20, 30]     315
(30, 40]     306
(40, 50]     750
(50, 60]     284
(60, 70]     424
(70, 80]     526
(80, 90]     835
(90, 100]    852
```

In [17]:
df = pd.DataFrame(np.random.RandomState(8765).randint(1, 101, size=(100, 2)), columns = ["A", "B"])
print(df)
bins = range(0, 101, 10)

# Use cut to create bins and groupby to calculate the sum for each group in column 'B'
result = df.groupby(pd.cut(df['A'], bins=bins, right=False))['B'].sum()
result

     A   B
0   46  29
1   75  22
2   49  63
3   33  43
4   71  75
..  ..  ..
95  60  87
96  57  40
97  86  19
98  50  56
99  97  94

[100 rows x 2 columns]


A
[0, 10)      635
[10, 20)     335
[20, 30)     340
[30, 40)     296
[40, 50)     676
[50, 60)     281
[60, 70)     511
[70, 80)     456
[80, 90)     806
[90, 100)    788
Name: B, dtype: int32

## DataFrames: harder problems 

### These might require a bit of thinking outside the box...

...but all are solvable using just the usual pandas/NumPy methods (and so avoid using explicit `for` loops).

Difficulty: *hard*

**29.** Consider a DataFrame `df` where there is an integer column 'X':
```python
df = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})
```
For each value, count the difference back to the previous zero (or the start of the Series, whichever is closer). These values should therefore be 

```
[1, 2, 0, 1, 2, 3, 4, 0, 1, 2]
```

Make this a new column 'Y'.

In [20]:
df = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})
zero_mask = df['X'] == 0

# Create a column 'Y' with the desired values
df['Y'] = zero_mask.groupby((zero_mask & ~zero_mask.shift(fill_value=False)).cumsum()).cumsum()

# Display the result
print(df['Y'].tolist())

[0, 0, 1, 1, 1, 1, 1, 1, 1, 1]


**30.** Consider the DataFrame constructed below which contains rows and columns of numerical data. 

Create a list of the column-row index locations of the 3 largest values in this DataFrame. In this case, the answer should be:
```
[(5, 7), (6, 4), (2, 5)]
```

In [7]:
df = pd.DataFrame(np.random.RandomState(30).randint(1, 101, size=(8, 8)))
print(df)
indices = df.unstack().nlargest(3).index.tolist()
print(indices)
result = [(index[0], index[1]) for index in indices]
# Display the result
print(result)


    0   1   2   3   4   5   6   7
0  38  38  46  46  13  24   3  54
1  18  47   4  42   8  66  50  46
2  62  36  19  19  77  17   7  63
3  28  47  46  65  63  12  16  24
4  14  51  34  56  29  59  92  79
5  58  76  96  45  38  76  58  40
6  10  34  48  40  37  23  41  26
7  55  70  91  27  79  92  20  31
[(2, 5), (5, 7), (6, 4)]


**31.** You are given the DataFrame below with a column of group IDs, 'grps', and a column of corresponding integer values, 'vals'.

```python
df = pd.DataFrame({"vals": np.random.RandomState(31).randint(-30, 30, size=15), 
                   "grps": np.random.RandomState(31).choice(["A", "B"], 15)})
```

Create a new column 'patched_values' which contains the same values as the 'vals' any negative values in 'vals' with the group mean:

```
    vals grps  patched_vals
0    -12    A          13.6
1     -7    B          28.0
2    -14    A          13.6
3      4    A           4.0
4     -7    A          13.6
5     28    B          28.0
6     -2    A          13.6
7     -1    A          13.6
8      8    A           8.0
9     -2    B          28.0
10    28    A          28.0
11    12    A          12.0
12    16    A          16.0
13   -24    A          13.6
14   -12    A          13.6
```

In [15]:
import pandas as pd
import numpy as np

# Create the DataFrame
df = pd.DataFrame({"vals": np.random.RandomState(31).randint(-30, 30, size=15), 
                   "grps": np.random.RandomState(31).choice(["A", "B"], 15)})

# Calculate group means
group_means = df.groupby('grps')['vals'].mean()

# Create the 'patched_values' column using np.where
df['patched_values'] = np.where(df['vals'] < 0, df['grps'].map(group_means), df['vals'])

# Display the DataFrame
print(df)


    vals grps  patched_values
0    -12    A       -0.333333
1     -7    B        6.333333
2    -14    A       -0.333333
3      4    A        4.000000
4     -7    A       -0.333333
5     28    B       28.000000
6     -2    A       -0.333333
7     -1    A       -0.333333
8      8    A        8.000000
9     -2    B        6.333333
10    28    A       28.000000
11    12    A       12.000000
12    16    A       16.000000
13   -24    A       -0.333333
14   -12    A       -0.333333


**32.** Implement a rolling mean over groups with window size 3, which ignores NaN value. For example consider the following DataFrame:

```python
>>> df = pd.DataFrame({'group': list('aabbabbbabab'),
                       'value': [1, 2, 3, np.nan, 2, 3, np.nan, 1, 7, 3, np.nan, 8]})
>>> df
   group  value
0      a    1.0
1      a    2.0
2      b    3.0
3      b    NaN
4      a    2.0
5      b    3.0
6      b    NaN
7      b    1.0
8      a    7.0
9      b    3.0
10     a    NaN
11     b    8.0
```
The goal is to compute the Series:

```
0     1.000000
1     1.500000
2     3.000000
3     3.000000
4     1.666667
5     3.000000
6     3.000000
7     2.000000
8     3.666667
9     2.000000
10    4.500000
11    4.000000
```
E.g. the first window of size three for group 'b' has values 3.0, NaN and 3.0 and occurs at row index 5. Instead of being NaN the value in the new column at this row index should be 3.0 (just the two non-NaN values are used to compute the mean (3+3)/2)

In [19]:
import pandas as pd
import numpy as np

# Create the DataFrame
df = pd.DataFrame({'group': list('aabbabbbabab'),
                   'value': [1, 2, 3, np.nan, 2, 3, np.nan, 1, 7, 3, np.nan, 8]})

# Define a custom rolling mean function that ignores NaN values
def custom_rolling_mean(series):
    return series.rolling(window=3, min_periods=1).mean()

# Apply the custom rolling mean function within each group
df['rolling_mean'] = df.groupby('group')['value'].apply(custom_rolling_mean)
df

group  value  rolling_mean
0      a    1.0      1.000000
1      a    2.0      1.500000
2      b    3.0      3.000000
3      b    NaN      3.000000
4      a    2.0      1.666667
5      b    3.0      3.000000
6      b    NaN      3.000000
7      b    1.0      2.000000
8      a    7.0      3.666667
9      b    3.0      2.000000
10     a    NaN      4.500000
11     b    8.0      4.000000

## Series and DatetimeIndex

### Exercises for creating and manipulating Series with datetime data

Difficulty: *easy/medium*

pandas is fantastic for working with dates and times. These puzzles explore some of this functionality.


**33.** Create a DatetimeIndex that contains each business day of 2015 and use it to index a Series of random numbers. Let's call this Series `s`.

In [49]:
import pandas as pd
import numpy as np

# Create a DatetimeIndex for each business day of 2015
business_days_2015 = pd.date_range(start='2015-01-01', end='2015-12-31', freq='B')

# Create a Series with random numbers indexed by the business days
s = pd.Series(np.random.randn(len(business_days_2015)), index=business_days_2015)

# Display the Series
print(s)

2015-01-01    0.943869
2015-01-02   -0.895628
2015-01-05   -0.087661
2015-01-06    0.849599
2015-01-07    1.924313
                ...   
2015-12-25   -0.718795
2015-12-28   -1.817932
2015-12-29    0.323542
2015-12-30    0.805758
2015-12-31   -1.276992
Freq: B, Length: 261, dtype: float64


**34.** Find the sum of the values in `s` for every Wednesday.

In [50]:
sums_on_wednesday = s.resample('W-WED').sum()
sums_on_wednesday

2015-01-07    2.734492
2015-01-14   -1.265246
2015-01-21    2.933390
2015-01-28   -5.506958
2015-02-04   -2.120460
2015-02-11   -0.787405
2015-02-18    2.611592
2015-02-25    2.863576
2015-03-04    2.599528
2015-03-11    2.438058
2015-03-18   -0.343920
2015-03-25    1.816213
2015-04-01    0.839711
2015-04-08    3.859923
2015-04-15    1.611139
2015-04-22    1.637407
2015-04-29   -0.773675
2015-05-06    0.571333
2015-05-13   -4.240928
2015-05-20   -1.489946
2015-05-27   -0.303807
2015-06-03    0.656672
2015-06-10   -1.137995
2015-06-17   -1.258563
2015-06-24    1.980213
2015-07-01    0.785644
2015-07-08    0.634775
2015-07-15    0.978910
2015-07-22    5.004225
2015-07-29   -5.210154
2015-08-05    1.522529
2015-08-12    1.134557
2015-08-19    0.368299
2015-08-26    2.123655
2015-09-02   -1.399399
2015-09-09    0.487789
2015-09-16   -3.493307
2015-09-23    3.039790
2015-09-30   -2.997442
2015-10-07   -0.270170
2015-10-14    0.040075
2015-10-21   -2.712449
2015-10-28    0.605671
2015-11-04 

**35.** For each calendar month in `s`, find the mean of values.

In [51]:
# Resample the Series to get the mean for each calendar month
mean_per_month = s.resample('M').mean()

# Display the result
print(mean_per_month)

2015-01-31   -0.059892
2015-02-28    0.209944
2015-03-31    0.183109
2015-04-30    0.373848
2015-05-31   -0.195043
2015-06-30    0.069339
2015-07-31   -0.009651
2015-08-31    0.149806
2015-09-30   -0.117437
2015-10-31   -0.085778
2015-11-30    0.108962
2015-12-31    0.135291
Freq: M, dtype: float64


**36.** For each group of four consecutive calendar months in `s`, find the date on which the highest value occurred.

In [52]:
# Resample the Series to get the date on which the highest value occurred for each group of four consecutive months
max_date_per_group = s.groupby(pd.Grouper(freq='M')).idxmax().resample('4M').first()

# Display the result
print(max_date_per_group)

2015-01-31   2015-01-16
2015-05-31   2015-02-23
2015-09-30   2015-06-30
2016-01-31   2015-10-09
Freq: 4M, dtype: datetime64[ns]


**37.** Create a DateTimeIndex consisting of the third Thursday in each month for the years 2015 and 2016.

In [54]:
# Create a DateTimeIndex for the third Thursday in each month for the years 2015 and 2016
third_thursdays = pd.date_range(start='2023-01-01', end='2023-12-31', freq='WOM-3THU')

# Display the result
print(third_thursdays)

DatetimeIndex(['2023-01-19', '2023-02-16', '2023-03-16', '2023-04-20',
               '2023-05-18', '2023-06-15', '2023-07-20', '2023-08-17',
               '2023-09-21', '2023-10-19', '2023-11-16', '2023-12-21'],
              dtype='datetime64[ns]', freq='WOM-3THU')


## Cleaning Data

### Making a DataFrame easier to work with

Difficulty: *easy/medium*

It happens all the time: someone gives you data containing malformed strings, Python, lists and missing data. How do you tidy it up so you can get on with the analysis?

Take this monstrosity as the DataFrame to use in the following puzzles:

```python
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm', 
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )', 
                               '12. Air France', '"Swiss Air"']})
```
Formatted, it looks like this:

```
            From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)
1      MAdrid_miLAN           NaN            []    <Air France> (12)
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis           NaN          [13]       12. Air France
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"
```


(It's some flight data I made up; it's not meant to be accurate in any way.)


**38.** Some values in the the **FlightNumber** column are missing (they are `NaN`). These numbers are meant to increase by 10 with each row so 10055 and 10075 need to be put in place. Modify `df` to fill in these missing numbers and make the column an integer column (instead of a float column).

In [55]:
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm', 
                               'Budapest_PaRis', 'Brussels_londOn'],
                   'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
                   'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )', 
                               '12. Air France', '"Swiss Air"']})

# Fill in missing values in the 'FlightNumber' column and convert to integers
df['FlightNumber'] = df['FlightNumber'].interpolate().astype(int)

# Display the modified DataFrame
print(df)

            From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris         10045      [23, 47]               KLM(!)
1      MAdrid_miLAN         10055            []    <Air France> (12)
2  londON_StockhOlm         10065  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis         10075          [13]       12. Air France
4   Brussels_londOn         10085      [67, 32]          "Swiss Air"


**39.** The **From\_To** column would be better as two separate columns! Split each string on the underscore delimiter `_` to give a new temporary DataFrame called 'temp' with the correct values. Assign the correct column names 'From' and 'To' to this temporary DataFrame. 

In [56]:
# Split the 'From_To' column into two separate columns
temp = df['From_To'].str.split('_', expand=True)

# Assign the correct column names to the temporary DataFrame
temp.columns = ['From', 'To']

# Display the temporary DataFrame
print(temp)

       From         To
0    LoNDon      paris
1    MAdrid      miLAN
2    londON  StockhOlm
3  Budapest      PaRis
4  Brussels     londOn


**40.** Notice how the capitalisation of the city names is all mixed up in this temporary DataFrame 'temp'. Standardise the strings so that only the first letter is uppercase (e.g. "londON" should become "London".)

In [57]:
# Capitalize the first letter of each string in the 'From' and 'To' columns
temp['From'] = temp['From'].str.capitalize()
temp['To'] = temp['To'].str.capitalize()

# Display the modified 'temp' DataFrame
print(temp)

       From         To
0    London      Paris
1    Madrid      Milan
2    London  Stockholm
3  Budapest      Paris
4  Brussels     London


**41.** Delete the **From_To** column from `df` and attach the temporary DataFrame 'temp' from the previous questions.

In [58]:
# Delete the 'From_To' column from df
df.drop('From_To', axis=1, inplace=True)

# Concatenate the 'temp' DataFrame to df
df = pd.concat([df, temp], axis=1)

# Display the modified DataFrame df
print(df)

   FlightNumber  RecentDelays              Airline      From         To
0         10045      [23, 47]               KLM(!)    London      Paris
1         10055            []    <Air France> (12)    Madrid      Milan
2         10065  [24, 43, 87]  (British Airways. )    London  Stockholm
3         10075          [13]       12. Air France  Budapest      Paris
4         10085      [67, 32]          "Swiss Air"  Brussels     London


**42**. In the **Airline** column, you can see some extra puctuation and symbols have appeared around the airline names. Pull out just the airline name. E.g. `'(British Airways. )'` should become `'British Airways'`.

In [59]:
# Remove extra punctuation and symbols from the 'Airline' column
df['Airline'] = df['Airline'].str.replace('[^a-zA-Z\s]', '', regex=True)

# Display the modified DataFrame df
print(df)

   FlightNumber  RecentDelays           Airline      From         To
0         10045      [23, 47]               KLM    London      Paris
1         10055            []       Air France     Madrid      Milan
2         10065  [24, 43, 87]  British Airways     London  Stockholm
3         10075          [13]        Air France  Budapest      Paris
4         10085      [67, 32]         Swiss Air  Brussels     London


**43**. In the RecentDelays column, the values have been entered into the DataFrame as a list. We would like each first value in its own column, each second value in its own column, and so on. If there isn't an Nth value, the value should be NaN.

Expand the Series of lists into a DataFrame named `delays`, rename the columns `delay_1`, `delay_2`, etc. and replace the unwanted RecentDelays column in `df` with `delays`.

In [60]:
# Expand the Series of lists into a DataFrame
delays = pd.DataFrame(df['RecentDelays'].to_list(), columns=[f'delay_{i+1}' for i in range(df['RecentDelays'].apply(len).max())])

# Concatenate delays DataFrame with the original DataFrame df
df = pd.concat([df, delays], axis=1)

# Drop the original 'RecentDelays' column from df
df.drop('RecentDelays', axis=1, inplace=True)

# Display the modified DataFrame df
print(df)

   FlightNumber           Airline      From         To  delay_1  delay_2  \
0         10045               KLM    London      Paris     23.0     47.0   
1         10055       Air France     Madrid      Milan      NaN      NaN   
2         10065  British Airways     London  Stockholm     24.0     43.0   
3         10075        Air France  Budapest      Paris     13.0      NaN   
4         10085         Swiss Air  Brussels     London     67.0     32.0   

   delay_3  
0      NaN  
1      NaN  
2     87.0  
3      NaN  
4      NaN  


The DataFrame should look much better now.
```
   FlightNumber          Airline      From         To  delay_1  delay_2  delay_3
0         10045              KLM    London      Paris     23.0     47.0      NaN
1         10055       Air France    Madrid      Milan      NaN      NaN      NaN
2         10065  British Airways    London  Stockholm     24.0     43.0     87.0
3         10075       Air France  Budapest      Paris     13.0      NaN      NaN
4         10085        Swiss Air  Brussels     London     67.0     32.0      NaN
```